### PR TITLE
Fix compile warnings

### PR DESCRIPTION
**Pull request by GMagician**
I get some warnings 'assigment from incompatible pointer type' in code like

```c++
static volatile uint8_t *u8g_data_port[8];

u8g_data_port[0] = portOutputRegister(digitalPinToPort(u8g->pin_list[U8G_PI_D0]));
```

this PR fix it

### CODE REVIEW

**Comment by ladyada** [comment]
its a 32 bit register

**Comment by GMagician** [comment]
out.reg is uint8_7 in header

**Comment by ladyada** [comment]
where is that? its should be 32 bit according to the datasheet?

**Comment by GMagician** [comment]
ops....maybe "go to definition" bring my to wrond typedef..

**Pull request closed without merging**
