### PR TITLE
Do not install CPX drivers on Windows 10

### PR DESCRIPTION
**Pull request by dhalbert**
These are the identical changes pushed as https://github.com/arduino/ArduinoCore-samd/pull/346 and https://github.com/arduino/ArduinoCore-samd/pull/338, to prevent the CPX driver installer from running on Windows 10, to fix https://github.com/arduino/ArduinoCore-samd/issues/336.

As of this moment arduino/ArduinoCore-samd hasn't been released as a new version yet, but we should anticipate that by fixing this in our own BSP now.

### CODE REVIEW

**Comment by dhalbert** [comment]
@ladyada also ping on this, to prevent further CPX problems on Windows 7. Essentially identical PR submitted to arduino/ArduinoCore-samd

**Comment by dhalbert** [comment]
@ladyada ping on the touch-up fixes on this PR, that fix WebUSB null driver install on Win7

**Comment by ladyada** [comment]
yeep sorry

**Comment by ladyada** [comment]
tested on win 7, installed CPX drivers right!

**Comment by dhalbert** [comment]
@ladyada should I make an Arduino release out of this? (have to remember how to do that)

**Comment by ladyada** [comment]
yah do you want to learn how?

**Pull request merged**
