### PR TITLE
Fix EINT listing for pin 4

### PR DESCRIPTION
**Pull request by matt-chan**
I think this file doesn't match the circuit diagram listing at https://cdn-learn.adafruit.com/assets/assets/000/047/156/original/circuit_playground_Adafruit_Circuit_Playground_Express_Pinout.png?1507829017.

It causes the interrupt pin checking code in ArduinoLowPower to fail, meaning it won't listen to interrupts from button A. Button B works fine.

### CODE REVIEW

**Comment by matt-chan** [comment]
There's a bunch of other mismatches as well, on D8, D11, A4, SDA, SDL. I don't know if this is a deliberate design decision.

**Comment by ladyada** [comment]
we probably just forgot them - would you like to update all of the INTs in one PR?

**Comment by matt-chan** [comment]
Sure. I just committed them.

**Comment by matt-chan** [comment]
It looks like the failed CI step (hallowing) is because of a download failure. Is there some way to restart it?

**Comment by ladyada** [comment]
kicked build!
@hathach please review when ya have a chance

**Review by hathach — APPROVED** [review]
PR is spot on with datasheet. Thank you

**Pull request merged**
