### PR TITLE
Some fixes to the startup code - clocks configs

### PR DESCRIPTION
**Pull request by aryelevin**
Reverted 1MHz clock generator to GCLK5 instead GCLK7.
Fixed the clock divider of 1MHz clock generator to be 48 (its source is DFLL which clocking at 48MHz, so 48 / 48 = 1, it was 48 / 24 = 2).
Updated the PLLs to the proper Ratio after the change of the 1MHz clock source.
Disabled GCLK_GENCTRL_DIVSEL reg on the 12MHz clock generator, since this caused the clock to be 1.5MHz.

### CODE REVIEW

**Comment by sajattack** [comment]
I was initially quite startled when you changed the PLL's, but I see that gclk5 is now 1MHz not 2MHz. I'd be curious as to why that happened, and I know it's not your doing.

**Comment by aryelevin** [comment]
From the defines it seems that it should be 1MHz not 2MHz, that's why I did it.

**Comment by sajattack** [comment]
Yeah I see that, I'm just wondering why it was ever 2MHz to begin with.

**Comment by aryelevin** [comment]
I don't know, but also the 12MHz one was seems to be completely wrong with the GCLK_GENCTRL_DIVSEL, which in result makes it just 1.5MHz.
Also, I'm very interested to know why Gen5 changed to Gen7? At the moment, no one answered that.

**Comment by ladyada** [comment]
yeah i dont know why it was changed to gen7 - not sure we'll ever find out the reason :)

**Comment by aryelevin** [comment]
I discovered all this while I'm trying to interface the SDHC interface, and the clock sources what wrong somehow, so I investigated this, and found all this issues.

**Comment by ladyada** [comment]
nows a good time to try fixing it - if it breaks something else we'll find out soon :)

**Comment by aryelevin** [comment]
😂 
True, lets see...
In my (basic) test, it works very well..

**Comment by sajattack** [comment]
Yeah I was about to file an issue for DIVSEL when I saw yours. I'm working on clock stuff for a Rust HAL for samd51.

**Comment by aryelevin** [comment]
Great, so we're all on the same page..

**Comment by ladyada** [comment]
saj, dya wanna try testing this before we merge?

**Comment by sajattack** [comment]
Sure, I already have code that puts clocks out on pins for measurement.

**Comment by sajattack** [comment]
@ladyada I'm not familiar with how to tell the arduino ide to use the right version of this repo.

**Comment by aryelevin** [comment]
@sajattack I'm working with Atmel studio, and I cannot help either about it.
Try to replace the file on the disk...

**Comment by ladyada** [comment]
@sajattack you uninstall the BSP from arduino, then clone this repo into ArduinoSketches/libraries/hardware/Adafruit

**Comment by sajattack** [comment]
I may have figured out why gclk5 was changed to gclk7. All the GCLK_IO for gclk5 is connected to flash on Metro M4.

**Comment by ladyada** [comment]
lol good find :) the GCLKs should be mixable is there any reason we cant stick to 7 and fix any typos on it?

**Comment by aryelevin** [comment]
OK, I'm also fine with it, just making sure everything is changed correctly.
Shall I commit another update?

**Comment by sajattack** [comment]
Same with GCLK 4 actually, I'll have to route stuff through another GCLK to put this stuff out onto pins.

**Comment by aryelevin** [comment]
If so, Maybe this isn't reason?

**Comment by sajattack** [comment]
I'm having difficulty with the arduino ide not being able to find "sam.h" I'm just gonna copy the clock configs @aryelevin made into a sketch on another gclk and call it a day.

**Comment by ladyada** [comment]
sorry to hear that - arduino has a lot of 'magic' going on

**Comment by sajattack** [comment]
Ok, I have confirmed that the clock configurations in this PR produce 12MHz, 1MHz, 120MHz, and 100MHz, as desired.

**Comment by ladyada** [comment]
thanks!

**Comment by aryelevin** [comment]
👍 Happy to help. 😎

**Pull request merged**
