### PR TITLE
revert bossac tool from 1.9 back to 1.8

### PR DESCRIPTION
**Pull request by hathach**
move blm badge up in boards.txt, update id for portal m4

### CODE REVIEW

**Review by ladyada — APPROVED** [review]

**Comment by dhalbert** [comment]
No complaints but what was the reason for reverting bossac back to 1.8?

**Comment by hathach** [comment]
@dhalbert user report upload issue with samd21 on macos. It seems to be issue with bossac 1.9 binaries on mac. I am not entirely, we will try to revert this first, and spend more time looking at it later on. having not install the latest is not user friendly at all.

**Comment by dhalbert** [comment]
Thanks, I was just helping someone else with the same issue, and see multiple reports in the forums.

**Comment by kaysievers** [comment]
It's probably this issue: https://github.com/shumatech/BOSSA/pull/150

**Comment by hathach** [comment]
Thank you @kaysievers , it is probably the root cause, in this case, I don’t see any other way than waiting for your PR to be merged. Here is the forum report
- https://forums.adafruit.com/viewtopic.php?f=19&t=187831
- https://forums.adafruit.com/viewtopic.php?f=57&t=187924

**Pull request merged**
