### PR TITLE
Force linker to use newer Arduino-provided versions of libarm_cortexM4lf_math.a

### PR DESCRIPTION
**Pull request by rlcamp**
Proposed solution to https://github.com/adafruit/ArduinoCore-samd/issues/201

### CODE REVIEW

**Comment by ladyada** [comment]
aweseomme.. we have a super big favor to ask - could you add an example that 'tests' that the math library is linking? that way when the CMSIS path changes in the future we have a test that will catch it

**Comment by rlcamp** [comment]
The following will fail to link if the old version of the .a file is found.

#include <arm_math.h>

arm_rfft_fast_instance_f32 plan;

void setup() {
  arm_rfft_fast_init_f32(&plan, 256);
}

void loop() {
    float in[256] = { 0 }, out[256] = { 0 };
    arm_rfft_fast_f32(&plan, in, out, 0);
}

[test_cmsis_fast_rfft.ino.txt](https://github.com/adafruit/ArduinoCore-samd/files/4028872/test_cmsis_fast_rfft.ino.txt)

**Comment by ladyada** [comment]
ok cool - i added that test and verified it does not pass CI
https://github.com/adafruit/ArduinoCore-samd/runs/376823304
!

**Comment by ladyada** [comment]
can you push a trivial change (extra space in a comment or something) to force a re-run of CI? we cant manually trigger actions yet

**Comment by ladyada** [comment]
nice!

**Pull request merged**
