### PR TITLE
[SAMD51] Add software calibration init on startup

### PR DESCRIPTION
**Pull request by GMagician**
Use calibration software area fuses to initialize devices

### CODE REVIEW

**Comment by GMagician** [comment]
Fix #126

**Comment by ladyada** [comment]
cool! thanks :)

**Comment by GMagician** [comment]
[OT] @ladyada I see PR older than 6 month, not yet merged, what is life status of this repository?

**Comment by ladyada** [comment]
it is alive

**Comment by GMagician** [comment]
@ladyada is there any problem with this PR? It's almost 1 month that it is posted

**Comment by ladyada** [comment]
we haven't had time to test it, how did you test the functionality has changed, what is different?

**Comment by GMagician** [comment]
Not tested since I'm using released version. But code is almost similar to what already present on samd21 and it's required by datasheet. So I'm almost sure it will work

**Comment by ladyada** [comment]
please test it and let us know, we dont accept untested PRs

**Comment by GMagician** [comment]
@ladyada I'm loading my code to see what happens, but forgive my pedantry, you say:

> we haven't had time to test it

and then

> we dont accept untested PRs

but if you have to test it before merge, what difference make my tests results?

**Comment by ladyada** [comment]
if people submit PRs, they must test it themselves - to make sure the code works, doesn't break existing code, and doesn't have bugs. this is minimum!
once the code has been tested by the submitter, when we have time, we also test the PR.
we get dozens of PRs a week and thousands of people use our code, if something breaks, even in your PR, we are responsible to fix it. so we have to be very careful - thats good for everyone!

**Comment by GMagician** [comment]
Finally I have been able to test this code. Adc and usb are still working but I'm not able to see any difference.

**Comment by ladyada** [comment]
kk mysterious!

**Comment by GMagician** [comment]
On my board all adc calibration values are 0x07
usb values are 
  TRANSN=0x09
  TRANSP=0x19
  TRIM=0x06
but already present in register (using arduino to compile)

**Comment by GMagician** [comment]
> usb seems already programmed

I'm not sure but some calibration is done in usb `USBDevice_SAMD21G18x::calibrate` (but why samd51 uses samd21 class? there is a lot of confusion in this library) but maybe this can explain why I find already programmed registers in usb...

**But I've not found any adc calibration code.**

By the way doing it here is harmful

**Comment by GMagician** [comment]
Any idea about merging ETA?

**Comment by ladyada** [comment]
i thought you were saying there's no difference?

**Comment by GMagician** [comment]
usb side no because it's already done by class above reported...adc can't appreciate difference but since who made the chip says it has to be done, maybe it's a good idea to do it

**Comment by ladyada** [comment]
oki we can try it

**Pull request merged**
